[application]

[web.app]

# HTML title tag content
title = "bussing-all-over-the-place-the-final-version"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
